<?php

/**
 * Implements hook_xmlrpc().
 */
function probe_xmlrpc() {
  $methods[] =  array(
    'probe', // First argument is the method name.
    'probe_xml_request', // Callback to execute when this method is requested.
    array( // An array defines the types of output and input values for this method.
      'array', // The first value is the return type, an array in this case.
      'array', // An array with requested variables.
    ),
    t('Exposes this website\'s internal details for monitoring updates, logs and other metadata. Access is only granted if the requester\'s IP is whitelisted or has sent a valid "probe_key".'),
  );

  return $methods;
}

/**
 * Callback for probe_xmlrpc().
 */
function probe_xml_request($variables = array()) {
  $controller = new \Drupal\probe\Controller\ProbeController();
  return $controller->probe($variables);
}
